<<<<<<<< HEAD:.github/workflows/Update_Issuers_TA_Database_with_Google_Sheets_Data.yml
name: Update Issuers TA Database with Google Sheets Data
========
name: Sheet to SQL Database
>>>>>>>> 19bfdc4836497caaef74ddce4c6b3e76a486403d:.github/workflows/Old-Historical-Workflows/12-5-24/sheet_to_sql.yml

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

concurrency: 
  group: database-update

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Python Dependencies
      run: |
        pip install gspread oauth2client
    
    - name: Read Google Sheet and Write to SQL Database
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
      run: |
        python 'src/scripts/Update_Issuers_TA_DB/update_db_with_Google_Sheets_Data.py'

    - name: Change Primary Key in Database
      run: python src/scripts/Update_Issuers_TA_DB/change_primary_key_to_cik.py
    
    - name: Commit and Push Database Files
      run: |
<<<<<<<< HEAD:.github/workflows/Update_Issuers_TA_Database_with_Google_Sheets_Data.yml
        git config --global user.name 'JamesAlfonse'
        git config --global user.email 'jamesalfonse@gmail.com'
        git add 'data/Issuers_TA/Issuers_TA.db' 'data/Issuers_TA/Issuers_TA.json'  # Add both the database and the JSON file
========
        git config --global user.name 'DRRUTHSEX'
        git config --global user.email 'drsf500@gmail.com'
        git add 'data/Main_Database.db' 'data/Main_Database.json'  # Add both the database and the JSON file
>>>>>>>> 19bfdc4836497caaef74ddce4c6b3e76a486403d:.github/workflows/Old-Historical-Workflows/12-5-24/sheet_to_sql.yml
        git commit -m "Updated database and JSON files" -a || echo "No changes to commit."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}